### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by zeropointnothing**
Added new commands, showfiles, disfile, dwlfile, getscreen.

### CODE REVIEW

**Review by zeropointnothing — COMMENTED** [review]
MultiConnect itself is running smoothly. win10toast issue will be fixed for the EXE.

**Comment by ZeroPointNothing** [comment]
win10toast module fixed plus 0.2.0 released

**Comment by bhqmz2333** [comment]
Hello!
I also encountered this issue, but after installing version 0.2.0, still have this error.
The operating system I use is Windows 7. On my computer, it can display notifications normally, but when it is destroyed, it still throws an exception.

WNDPROC return value cannot be converted to LRESULT
TypeError: WPARAM is simple, so must be an int object (got NoneType)

After installing version 0.2.0, the "threaded" parameter cannot be passed in, which means that multithreading cannot be enabled.

I'm sure it has nothing to do with software packages.

Because when I commented on the call to the software package (PyQt5.QtWidgets.QApplication in pygui), this problem still exists.
Image_PyCharmRunImage
Note that I have installed version 0.2.0
Image_PipInstallImage

I want to know what happened.
If it can be repaired, please try to repair it.
Thanks!

**Comment by zeropointnothing** [comment]
The package returns a value of None when the notification is destroyed,  raising an error. I don't know why this is an issue, but I fixed it by manually changing the return value to 0 instead.

**Comment by zeropointnothing** [comment]
The odd thing about it all, is that the creators are aware of it, or there is an issue on their GitHub, at least. This should work on most devices (Windows 10 and 11 being the only tested ones at the moment). For now though, the simple fix should suffice. - Refer to the issue I posted on this matter for more info.

**Pull request merged**
